### ISSUE TITLE
[BUG] Chat messages are bugged

### ISSUE THREAD

**Issue by J0Santos** [Dmarceli/42_Cursus_Transcendence#117]
![image](https://github.com/Dmarceli/42_Cursus_Transcendence/assets/78555896/cdbf8cd3-44a7-4c1a-8a4e-2970724d289e)

**Comment by J0Santos** [comment]
conversa com 2 pessoas. Isto e no raquetas.pt

**Comment by J0Santos** [comment]
no da Maria esta bem, no meu ecra nao

**Comment by Dmarceli** [comment]
como e que se replica?

**Comment by J0Santos** [comment]
Eu ontem ainda tive a tentar replicar, mas não consegui mais. O gonçalo tbm disse que uma vez aconteceu lhe o mesmo, mas a unica coisa que ele fez foi fazer make re e depois ficou bom.
Se acharem que é tranquilo pode se fechar o issue.

**Comment by ncameiri42** [comment]
Não é possivel replicar
