### ISSUE TITLE
Need fixing console error

### ISSUE THREAD

**Issue by J0Santos** [Dmarceli/42_Cursus_Transcendence#161]
![image](https://github.com/Dmarceli/42_Cursus_Transcendence/assets/78555896/1509da84-8dc8-44d4-9a6b-d55c689e38c3)

**Comment by Dmarceli** [comment]
por favor, quando abrem issues metam como o replicar

**Comment by J0Santos** [comment]
Neste caso não há como replicar. O erro aparece logo quando se faz make.

**Comment by Dmarceli** [comment]
Então mas isso é um erro na consola do browser

**Comment by J0Santos** [comment]
Honey Extension on Firefox was giving the error
