### ISSUE TITLE
[FRONTEND LIGHT MODE] Problem when using light mode user profile, letters white colour

### ISSUE THREAD

**Issue by ncameiri** [Dmarceli/42_Cursus_Transcendence#81]
![Image](https://github.com/Dmarceli/42_Cursus_Transcendence/assets/74956154/985441cf-ce6f-4c2a-b893-7feb9708a088)

**Comment by ncameiri42** [comment]
![Image](https://github.com/Dmarceli/42_Cursus_Transcendence/assets/74956154/784ca9ac-3a92-48cb-9783-4d0f1d080160)
